### ISSUE TITLE
[29] Rate limit reached

### ISSUE THREAD

**Issue by Dimoon12** [solkogan/searchface#2]
[29] Rate limit reached при работе DownloadPhotosToJpg_2.py
после 998 начинается куча 29 ошибок

**Comment by Dmitrisv** [comment]
Это ошибка со стороны вк так как там ограничения по запросам

**Comment by solkogan** [comment]
Это нужно как то научиться обходить
Можно попробовать ставить рандомную паузу - или менять прокси / аккаунты ВК
